// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWtofMtesTrBGOxvLBlxQQp9OmqcmtOdc',
    appId: '1:1021315459545:web:52ba64f72e4ff813d751c8',
    messagingSenderId: '1021315459545',
    projectId: 'mart-jio-online',
    authDomain: 'mart-jio-online.firebaseapp.com',
    storageBucket: 'mart-jio-online.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7YC1t40EqE73h710Mg4JlSDJtgVQpJ40',
    appId: '1:1021315459545:android:b407a3737c5f8018d751c8',
    messagingSenderId: '1021315459545',
    projectId: 'mart-jio-online',
    storageBucket: 'mart-jio-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaqWfNjlHQpzOb_kONhfFqndZi-_aWRmM',
    appId: '1:1021315459545:ios:d0063ea60ca2d3f5d751c8',
    messagingSenderId: '1021315459545',
    projectId: 'mart-jio-online',
    storageBucket: 'mart-jio-online.firebasestorage.app',
    iosBundleId: 'com.example.jiomartApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaqWfNjlHQpzOb_kONhfFqndZi-_aWRmM',
    appId: '1:1021315459545:ios:d0063ea60ca2d3f5d751c8',
    messagingSenderId: '1021315459545',
    projectId: 'mart-jio-online',
    storageBucket: 'mart-jio-online.firebasestorage.app',
    iosBundleId: 'com.example.jiomartApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWtofMtesTrBGOxvLBlxQQp9OmqcmtOdc',
    appId: '1:1021315459545:web:f2407e9ac6078472d751c8',
    messagingSenderId: '1021315459545',
    projectId: 'mart-jio-online',
    authDomain: 'mart-jio-online.firebaseapp.com',
    storageBucket: 'mart-jio-online.firebasestorage.app',
  );
}
